// <auto-generated />
using System;
using ExerciseAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ExerciseAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260714114000_AddWorkoutTemplates")]
    partial class AddWorkoutTemplates
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ExerciseAPI.Models.Exercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Abs")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Biceps")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Calves")
                        .HasColumnType("numeric");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("ChestMain")
                        .HasColumnType("numeric");

                    b.Property<decimal>("CoreStabilizers")
                        .HasColumnType("numeric");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ExternalId")
                        .HasColumnType("text");

                    b.Property<decimal>("Forearms")
                        .HasColumnType("numeric");

                    b.Property<string>("GifUrl")
                        .HasColumnType("text");

                    b.Property<decimal>("Glutes")
                        .HasColumnType("numeric");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsBenchmark")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Lats")
                        .HasColumnType("numeric");

                    b.Property<decimal>("LowerBack")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Quadriceps")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Hamstrings")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Rhomboids")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Triceps")
                        .HasColumnType("numeric");

                    b.Property<decimal>("DeltoidAnterior")
                        .HasColumnType("numeric");

                    b.Property<decimal>("DeltoidLateral")
                        .HasColumnType("numeric");

                    b.Property<decimal>("DeltoidPosterior")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Exercises");
                });

            modelBuilder.Entity("ExerciseAPI.Models.ExerciseMuscleGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ExerciseId")
                        .HasColumnType("integer");

                    b.Property<string>("MuscleGroupKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Activation")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.ToTable("ExerciseMuscleGroups");
                });

            modelBuilder.Entity("ExerciseAPI.Models.MuscleGroup", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("text");

                    b.Property<string>("NamePl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsFront")
                        .HasColumnType("boolean");

                    b.Property<int>("HalfLife")
                        .HasColumnType("integer");

                    b.HasKey("Key");

                    b.ToTable("MuscleGroups");
                });

            modelBuilder.Entity("ExerciseAPI.Models.PersonalRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Weight")
                        .HasColumnType("numeric");

                    b.Property<int>("Reps")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("UserId");

                    b.ToTable("PersonalRecords");
                });

            modelBuilder.Entity("ExerciseAPI.Models.UserExercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("integer");

                    b.Property<int?>("RIR")
                        .HasColumnType("integer");

                    b.Property<int?>("RPE")
                        .HasColumnType("integer");

                    b.Property<int?>("Reps")
                        .HasColumnType("integer");

                    b.Property<int?>("Sets")
                        .HasColumnType("integer");

                    b.Property<int?>("StartMode")
                        .HasColumnType("integer");

                    b.Property<int?>("Status")
                        .HasColumnType("integer");

                    b.Property<int?>("TemplateId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("Date");

                    b.HasIndex("UserId", "Date");

                    b.ToTable("UserExercise");
                });

            modelBuilder.Entity("ExerciseAPI.Models.WorkoutTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("WorkoutTemplates");
                });

            modelBuilder.Entity("ExerciseAPI.Models.TemplateExercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("TemplateId")
                        .HasColumnType("integer");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("integer");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("TemplateId", "Order");

                    b.ToTable("TemplateExercises");
                });

            modelBuilder.Entity("ExerciseAPI.Models.ExerciseMuscleGroup", b =>
                {
                    b.HasOne("ExerciseAPI.Models.Exercise", "Exercise")
                        .WithMany("MuscleGroupMappings")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");
                });

            modelBuilder.Entity("ExerciseAPI.Models.PersonalRecord", b =>
                {
                    b.HasOne("ExerciseAPI.Models.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");
                });

            modelBuilder.Entity("ExerciseAPI.Models.UserExercise", b =>
                {
                    b.HasOne("ExerciseAPI.Models.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");
                });

            modelBuilder.Entity("ExerciseAPI.Models.TemplateExercise", b =>
                {
                    b.HasOne("ExerciseAPI.Models.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExerciseAPI.Models.WorkoutTemplate", "Template")
                        .WithMany("TemplateExercises")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("ExerciseAPI.Models.Exercise", b =>
                {
                    b.Navigation("MuscleGroupMappings");
                });

            modelBuilder.Entity("ExerciseAPI.Models.WorkoutTemplate", b =>
                {
                    b.Navigation("TemplateExercises");
                });

#pragma warning restore 612, 618
        }
    }
}