// <auto-generated />
using System;
using ExerciseAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ExerciseAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260710093456_AddComprehensiveMuscleMapping")]
    partial class AddComprehensiveMuscleMapping
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ExerciseAPI.Models.Exercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GifUrl")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Exercises");
                });

            modelBuilder.Entity("ExerciseAPI.Models.ExerciseMuscleMapping", b =>
                {
                    b.Property<int>("ExerciseId")
                        .HasColumnType("integer");

                    b.Property<int>("MuscleId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Factor")
                        .HasColumnType("numeric");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ExerciseId", "MuscleId");

                    b.HasIndex("MuscleId");

                    b.ToTable("ExerciseMuscleMappings");
                });

            modelBuilder.Entity("ExerciseAPI.Models.Muscle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsFront")
                        .HasColumnType("boolean");

                    b.Property<string>("NameKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NamePl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Muscles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsFront = true,
                            NameKey = "chest_main",
                            NamePl = "Klatka piersiowa"
                        },
                        new
                        {
                            Id = 2,
                            IsFront = true,
                            NameKey = "deltoid_anterior",
                            NamePl = "Bark przedni"
                        },
                        new
                        {
                            Id = 3,
                            IsFront = true,
                            NameKey = "deltoid_lateral",
                            NamePl = "Bark boczny"
                        },
                        new
                        {
                            Id = 4,
                            IsFront = true,
                            NameKey = "biceps",
                            NamePl = "Biceps"
                        },
                        new
                        {
                            Id = 5,
                            IsFront = true,
                            NameKey = "forearms",
                            NamePl = "Przedramiona"
                        },
                        new
                        {
                            Id = 6,
                            IsFront = true,
                            NameKey = "abs",
                            NamePl = "Brzuch"
                        },
                        new
                        {
                            Id = 7,
                            IsFront = true,
                            NameKey = "quadriceps",
                            NamePl = "Czwórki"
                        },
                        new
                        {
                            Id = 8,
                            IsFront = true,
                            NameKey = "core_stabilizers",
                            NamePl = "Stabilizatory tułowia"
                        },
                        new
                        {
                            Id = 9,
                            IsFront = false,
                            NameKey = "lats",
                            NamePl = "Plecy szerokie"
                        },
                        new
                        {
                            Id = 10,
                            IsFront = false,
                            NameKey = "lower_back",
                            NamePl = "Dolny odcinek pleców"
                        },
                        new
                        {
                            Id = 11,
                            IsFront = false,
                            NameKey = "rhomboids_trapezius",
                            NamePl = "Romby i czworoboczny"
                        },
                        new
                        {
                            Id = 12,
                            IsFront = false,
                            NameKey = "deltoid_posterior",
                            NamePl = "Bark tylny"
                        },
                        new
                        {
                            Id = 13,
                            IsFront = false,
                            NameKey = "triceps",
                            NamePl = "Triceps"
                        },
                        new
                        {
                            Id = 14,
                            IsFront = false,
                            NameKey = "glutes",
                            NamePl = "Pośladki"
                        },
                        new
                        {
                            Id = 15,
                            IsFront = false,
                            NameKey = "hamstrings",
                            NamePl = "Dwugłowe uda"
                        },
                        new
                        {
                            Id = 16,
                            IsFront = false,
                            NameKey = "calves",
                            NamePl = "Łydki"
                        });
                });

            modelBuilder.Entity("ExerciseAPI.Models.UserExercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("integer");

                    b.Property<int?>("Reps")
                        .HasColumnType("integer");

                    b.Property<int?>("Sets")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("UserExercise");
                });

            modelBuilder.Entity("ExerciseAPI.Models.ExerciseMuscleMapping", b =>
                {
                    b.HasOne("ExerciseAPI.Models.Exercise", "Exercise")
                        .WithMany("MuscleMappings")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExerciseAPI.Models.Muscle", "Muscle")
                        .WithMany()
                        .HasForeignKey("MuscleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("Muscle");
                });

            modelBuilder.Entity("ExerciseAPI.Models.Exercise", b =>
                {
                    b.Navigation("MuscleMappings");
                });
#pragma warning restore 612, 618
        }
    }
}
