// <auto-generated />
using System;
using ExerciseAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ExerciseAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260713082921_AddRirAndDateIndex")]
    partial class AddRirAndDateIndex
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ExerciseAPI.Models.Exercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Abs")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Biceps")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Calves")
                        .HasColumnType("numeric");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("ChestMain")
                        .HasColumnType("numeric");

                    b.Property<decimal>("CoreStabilizers")
                        .HasColumnType("numeric");

                    b.Property<decimal>("DeltoidAnterior")
                        .HasColumnType("numeric");

                    b.Property<decimal>("DeltoidLateral")
                        .HasColumnType("numeric");

                    b.Property<decimal>("DeltoidPosterior")
                        .HasColumnType("numeric");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ExternalId")
                        .HasColumnType("text");

                    b.Property<decimal>("Forearms")
                        .HasColumnType("numeric");

                    b.Property<string>("GifUrl")
                        .HasColumnType("text");

                    b.Property<decimal>("Glutes")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Hamstrings")
                        .HasColumnType("numeric");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsBenchmark")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Lats")
                        .HasColumnType("numeric");

                    b.Property<decimal>("LowerBack")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Quadriceps")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Rhomboids")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Triceps")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Exercises");
                });

            modelBuilder.Entity("ExerciseAPI.Models.ExerciseMuscleGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ExerciseId")
                        .HasColumnType("integer");

                    b.Property<string>("MuscleGroupKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("WeightPercentage")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("MuscleGroupKey");

                    b.ToTable("ExerciseMuscleGroups");
                });

            modelBuilder.Entity("ExerciseAPI.Models.MuscleGroup", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("text");

                    b.Property<double>("HalfLife")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsFront")
                        .HasColumnType("boolean");

                    b.Property<string>("NamePl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Key");

                    b.ToTable("MuscleGroups");

                    b.HasData(
                        new
                        {
                            Key = "chest_main",
                            HalfLife = 42.0,
                            IsFront = true,
                            NamePl = "Klatka piersiowa"
                        },
                        new
                        {
                            Key = "deltoid_anterior",
                            HalfLife = 30.0,
                            IsFront = true,
                            NamePl = "Bark przedni"
                        },
                        new
                        {
                            Key = "deltoid_lateral",
                            HalfLife = 30.0,
                            IsFront = true,
                            NamePl = "Bark boczny"
                        },
                        new
                        {
                            Key = "deltoid_posterior",
                            HalfLife = 30.0,
                            IsFront = false,
                            NamePl = "Bark tylny"
                        },
                        new
                        {
                            Key = "biceps",
                            HalfLife = 30.0,
                            IsFront = true,
                            NamePl = "Biceps"
                        },
                        new
                        {
                            Key = "triceps",
                            HalfLife = 30.0,
                            IsFront = false,
                            NamePl = "Triceps"
                        },
                        new
                        {
                            Key = "forearms",
                            HalfLife = 24.0,
                            IsFront = true,
                            NamePl = "Przedramiona"
                        },
                        new
                        {
                            Key = "lats",
                            HalfLife = 42.0,
                            IsFront = false,
                            NamePl = "Plecy szerokie"
                        },
                        new
                        {
                            Key = "rhomboids",
                            HalfLife = 30.0,
                            IsFront = false,
                            NamePl = "Romby i czworoboczny"
                        },
                        new
                        {
                            Key = "lower_back",
                            HalfLife = 30.0,
                            IsFront = false,
                            NamePl = "Dolny odcinek pleców"
                        },
                        new
                        {
                            Key = "abs",
                            HalfLife = 24.0,
                            IsFront = true,
                            NamePl = "Brzuch"
                        },
                        new
                        {
                            Key = "core_stabilizers",
                            HalfLife = 24.0,
                            IsFront = true,
                            NamePl = "Stabilizatory tułowia"
                        },
                        new
                        {
                            Key = "quadriceps",
                            HalfLife = 42.0,
                            IsFront = true,
                            NamePl = "Czwórki"
                        },
                        new
                        {
                            Key = "hamstrings",
                            HalfLife = 30.0,
                            IsFront = false,
                            NamePl = "Dwugłowe uda"
                        },
                        new
                        {
                            Key = "glutes",
                            HalfLife = 42.0,
                            IsFront = false,
                            NamePl = "Pośladki"
                        },
                        new
                        {
                            Key = "calves",
                            HalfLife = 24.0,
                            IsFront = false,
                            NamePl = "Łydki"
                        });
                });

            modelBuilder.Entity("ExerciseAPI.Models.PersonalRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DietStatusAtTime")
                        .HasColumnType("integer");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("integer");

                    b.Property<int>("Reps")
                        .HasColumnType("integer");

                    b.Property<decimal?>("StrengthToWeightRatio")
                        .HasColumnType("numeric");

                    b.Property<int?>("UserAgeAtTime")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("UserWeightAtTime")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Weight")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("PersonalRecords");
                });

            modelBuilder.Entity("ExerciseAPI.Models.UserExercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("integer");

                    b.Property<int?>("RIR")
                        .HasColumnType("integer");

                    b.Property<int?>("RPE")
                        .HasColumnType("integer");

                    b.Property<int?>("Reps")
                        .HasColumnType("integer");

                    b.Property<int?>("Sets")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("UserId", "Date");

                    b.ToTable("UserExercise");
                });

            modelBuilder.Entity("ExerciseAPI.Models.ExerciseMuscleGroup", b =>
                {
                    b.HasOne("ExerciseAPI.Models.Exercise", "Exercise")
                        .WithMany("MuscleGroupMappings")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExerciseAPI.Models.MuscleGroup", "MuscleGroup")
                        .WithMany()
                        .HasForeignKey("MuscleGroupKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("MuscleGroup");
                });

            modelBuilder.Entity("ExerciseAPI.Models.Exercise", b =>
                {
                    b.Navigation("MuscleGroupMappings");
                });
#pragma warning restore 612, 618
        }
    }
}
